kind: pipeline
name: trader-gateway

steps:
  - name: test
    image: openjdk:8-jdk-alpine
    volumes:
      - name: maven-cache
        path: /root/.m2
    commands:
      - sleep 15
      - chmod +x ./mvnw && ./mvnw test -Dspring.profiles.active=droneCI && ./mvnw clean package -Dspring.profiles.active=droneCI
    when:
      branch:
        - master
        - master-*
        - dev


  - name: docker
    image: plugins/docker
    settings:
      username: zhiyuanma0401
      password:
        from_secret: zhiyuanma0401
      repo: registry-vpc.cn-hangzhou.aliyuncs.com/macoredroid/trader-gateway
      registry: registry-vpc.cn-hangzhou.aliyuncs.com
      tags:
        - v1.0.4
    when:
      branch:
        - master-*


volumes:
  - name: maven-cache
    host:
      path: /maven-cache
