spring:
  application:
    name: trade-gateway
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      uri: mongodb://mongodb-1592143854.traderone.svc.cluster.local:27017/otc
      authentication-database: admin
      username: root
      password: 1lnBhOWge0
  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 1
    timeout: 60s
    database: 0
  datasource:
    max-idle: 10
    max-wait: 1000
    min-idle: 5
    initial-size: 5

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

traderCompany: B

brokerWsM: broker-websocket-one.brokerone:8080
brokerWsN: broker-websocket-two.brokertwo:8080
brokerHttpM: http://broker-one.brokerone:8080
brokerttpN: http://broker-two.brokertwo:8080